# Generated by Django 3.0.2 on 2020-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Textil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
    ]
